### ISSUE TITLE
Add new node

### ISSUE THREAD

**Issue by Amrosx** [haraldng/omnipaxos#115]
May I know why that not accepting to add new nodes. I have modified the following lines in docker compose file, but not connected, s4, s5 not connected

```
version: "3.9"

x-common-variables: &common-variables
  RUST_BACKTRACE: 1
  NODES: "[1, 2, 3, 4, 5]"
  # NODES: "[1, 2, 3]"

services:
  network-actor:
    build: ./network_actor/
    container_name: network-actor
    hostname: net
    environment:
      <<: *common-variables
      PORT_MAPPINGS: "[[8013,8031],[8012,8021],[8023,8032],[8014,8041],[8015,8051]]"
      CLIENT_PORTS: "[8001, 8002, 8003, 8004, 8005]"
      # PORT_MAPPINGS: "[[8013,8031],[8012,8021],[8023,8032]]"
      # CLIENT_PORTS: "[8001, 8002, 8003]"
    ports: []
    stdin_open: true
    tty: true
  
  s1:
    build: ./kv_store/
    container_name: s1
    hostname: s1
    environment:
      <<: *common-variables
      PID: 1
    depends_on:
      - network-actor

  s2:
    build: ./kv_store/
    container_name: s2
    hostname: s2
    environment:
      <<: *common-variables
      PID: 2
    depends_on:
      - network-actor

  s3:
    build: ./kv_store/
    container_name: s3
    hostname: s3
    environment:
      <<: *common-variables
      PID: 3
    depends_on:
      - network-actor

  s4:
      build: ./kv_store/
      container_name: s4
      hostname: s4
      environment:
        <<: *common-variables
        PID: 4
      depends_on:
        - network-actor

  s5:
      build: ./kv_store/
      container_name: s5
      hostname: s5
      environment:
        <<: *common-variables
        PID: 5
      depends_on:
        - network-actor
```
