### ISSUE TITLE
Config and logging as features

### ISSUE THREAD

**Issue by Max-Meldrum** [haraldng/omnipaxos#44]
Just a suggestion as it would bring down ``omnipaxos_core`` to zero dependencies by default :smile: 

```toml
[features]
config = ["hocon"]
logging = ["slog", "slog_term", "slog_async"]
```
