### ISSUE TITLE
Documentation for features

### ISSUE THREAD

**Issue by haraldng** [haraldng/omnipaxos#74]
Add a page that describes all the different feature flags that can be set.

**Comment by Max-Meldrum** [comment]
For crates that are to be published, the following will highlight that structs/functions/traits are only available when a feature is enabled.

```toml
# Cargo.toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```
```rust
// lib.rs
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
```
